-- Actualizar la VIEW vehicle_posts_view para incluir todos los nuevos campos
-- Primero eliminamos la VIEW existente
DROP VIEW IF EXISTS public.vehicle_posts_view;

-- Creamos la VIEW actualizada con todos los campos
CREATE VIEW public.vehicle_posts_view AS
SELECT 
  id,
  titulo,
  slug,
  marca,
  modelo,
  version,
  anio,
  kilometraje,
  carroceria,
  condicion,
  color_exterior,
  color_interior,
  puertas,
  asientos,
  transmision,
  traccion,
  cilindrada,
  combustible,
  potencia_hp,
  moneda,
  precio,
  precio_negociable,
  estado,
  disponible,
  descripcion,
  images_urls,
  created_at,
  updated_at,
  created_by,
  destacado,
  pais,
  estado_provincia,
  ciudad,
  -- Campos nuevos de MOTOR
  alimentacion,
  cilindros,
  valvulas,
  -- Campos nuevos de TRANSMISIÓN Y CHASIS
  velocidades,
  neumaticos,
  frenos_delanteros,
  frenos_traseros,
  direccion_asistida,
  freno_mano,
  -- Campos nuevos de CONFORT
  aire_acondicionado,
  asiento_delantero_ajuste_altura,
  volante_regulable,
  asientos_traseros,
  tapizados,
  cierre_puertas,
  vidrios_delanteros,
  vidrios_traseros,
  espejos_exteriores,
  espejo_interior_antideslumbrante,
  faros_delanteros,
  faros_antiniebla,
  faros_tipo,
  computadora_abordo,
  control_velocidad_crucero,
  limitador_velocidad,
  llantas_aleacion,
  techo_solar,
  sensores_estacionamiento,
  camara_estacionamiento,
  asistencia_arranque_pendientes,
  -- Campos nuevos de SEGURIDAD
  abs,
  distribucion_electronica_frenado,
  asistencia_frenada_emergencia,
  airbags_delanteros,
  airbags_cortina,
  airbag_rodilla_conductor,
  airbags_laterales,
  cantidad_airbags,
  alarma,
  inmovilizador_motor,
  anclaje_asientos_infantiles,
  sensor_lluvia,
  sensor_luz,
  autobloqueo_puertas_velocidad,
  control_estabilidad,
  control_traccion,
  control_descenso,
  sensor_presion_neumaticos,
  -- Campos nuevos de COMUNICACIÓN Y ENTRETENIMIENTO
  equipo_musica,
  comandos_volante,
  conexion_auxiliar,
  conexion_usb,
  bluetooth,
  control_voz,
  pantalla,
  navegacion_gps,
  apple_carplay,
  android_auto,
  -- Campo calculado para precio_num (si existe)
  CASE 
    WHEN precio ~ '^[0-9]+(\.[0-9]+)?$' THEN CAST(precio AS NUMERIC)
    WHEN precio ~ '^[0-9,]+(\.[0-9]+)?$' THEN CAST(REPLACE(precio, ',', '') AS NUMERIC)
    ELSE NULL
  END AS precio_num
FROM public.vehicle_posts;

